---
# tasks file for mw.apache2
# APACHE
- name: install apache
  package:
    name: apache2
    state: present

#- name: www-data uid
#  ansible.builtin.user:
#    name: www-data
#    uid: 1101

- name:
  command: usermod -u 1101 www-data

- name: www-data gid
  ansible.builtin.group:
    name: www-data
    gid: 1100

#- name: Copy Apache2 conf
#  template:
#    src: templates/apache2/apache2.conf.j2
 #   dest: /etc/apache2/apache2.conf

#- name: Copy conf site
#  template:
#    src: templates/apache2/mediawiki.conf.j2
#    dest: /etc/apache2/sites-available/mediawiki.conf
#  notify: restart apache2
